SELECT I.ID, N.FISH_NAME, I.LENGTH
FROM FISH_INFO I JOIN FISH_NAME_INFO N
USING (FISH_TYPE)
WHERE (N.FISH_TYPE, I.LENGTH) IN (
    SELECT FISH_TYPE, MAX(LENGTH) AS LENGTH
    FROM FISH_INFO
    GROUP BY FISH_TYPE
)
ORDER BY I.ID;

---

WITH RESULT AS (
    SELECT ID, FISH_TYPE, LENGTH, ROW_NUMBER() OVER (PARTITION BY FISH_TYPE ORDER BY LENGTH DESC) AS NUM
    FROM FISH_INFO
)

SELECT I.ID, N.FISH_NAME, I.LENGTH
FROM RESULT I JOIN FISH_NAME_INFO N
USING (FISH_TYPE)
WHERE I.NUM = 1
ORDER BY I.ID;