SELECT I.ITEM_ID, I.ITEM_NAME, I.RARITY
FROM ITEM_INFO I JOIN ITEM_TREE T
ON I.ITEM_ID = T.ITEM_ID
WHERE T.PARENT_ITEM_ID IN (  -- 부모의 희귀도가 RARE인 아이템 구하기
    SELECT S.ITEM_ID
    FROM ITEM_INFO S
    WHERE RARITY = 'RARE'
)
ORDER BY ITEM_ID DESC